# Write your MySQL query statement below
SELECT 
    DISTINCT A.ID
FROM 
    WEATHER A, WEATHER B
WHERE 
    A.TEMPERATURE > B. TEMPERATURE
                AND 
    DATEDIFF(A.RECORDDATE,B.RECORDDATE)  = 1;

