# Write your MySQL query statement below
SELECT
    C.NAME
FROM
    CUSTOMER C
WHERE 
    C.REFEREE_ID != 2
        OR
    C.REFEREE_ID  IS NULL;



# SELECT CUSTOMER.NAME 
# FROM CUSTOMER
# WHERE NOT CUSTOMER.REFEREE_ID  = 2 
#         OR
#       CUSTOMER.REFEREE_ID  IS NULL;