# Write your MySQL query statement below
SELECT
    A.ACTIVITY_DATE AS DAY, COUNT(DISTINCT(A.USER_ID)) AS ACTIVE_USERS
FROM
    ACTIVITY A
WHERE 
     DATEDIFF('2019-07-27', A.ACTIVITY_DATE) < 30 AND DATEDIFF('2019-07-27', A.ACTIVITY_DATE) >= 0
GROUP BY
    A.ACTIVITY_DATE;
    
      
