# Write your MySQL query statement below
SELECT
    A.ACTIVITY_DATE AS DAY, COUNT(DISTINCT(A.USER_ID)) AS ACTIVE_USERS
FROM
    ACTIVITY A
WHERE 
    A.ACTIVITY_DATE <= '2019-07-27' AND  A.ACTIVITY_DATE > '2019-06-27'
GROUP BY
    A.ACTIVITY_DATE;
    
      
