# Write your MySQL query statement below

SELECT 
    E.EMPLOYEE_ID, IF(E.EMPLOYEE_ID%2 = 1 AND E.NAME NOT LIKE 'M%' ,E.SALARY,0) AS BONUS
FROM 
    EMPLOYEES E
ORDER BY
    E.EMPLOYEE_ID;


# SELECT EMPLOYEES.EMPLOYEE_ID,
# IF (EMPLOYEES.EMPLOYEE_ID%2 = 1 AND EMPLOYEES.NAME NOT LIKE 'M%',EMPLOYEES.SALARY, 0  ) AS BONUS
# FROM EMPLOYEES
# ORDER BY  EMPLOYEES.EMPLOYEE_ID
