# Write your MySQL query statement below

SELECT EMPLOYEES.EMPLOYEE_ID,
IF (EMPLOYEES.EMPLOYEE_ID%2 = 1 AND EMPLOYEES.NAME NOT LIKE 'M%',EMPLOYEES.SALARY, 0  ) AS BONUS
FROM EMPLOYEES
ORDER BY  EMPLOYEES.EMPLOYEE_ID
